class ImageConstants:

    DEFAULT_TARGET_HEIGHT = 600
    DEFAULT_BACKGROUND_TOLERANCE = 15
    DEFAULT_REGION_THRESHOLD = 2
    DEFAULT_SEED_OFFSET = 6
    DEFAULT_MINIMUM_ROOM_AREA = 300
    DEFAULT_OVERLAY_ALPHA = 0.45
    LINE_DETECTOR_MODE = 0
    FOUR_CONNECTED_NEIGHBORS = 4
    EIGHT_CONNECTED_NEIGHBORS = 8
